CREATE TABLE CLIENTE (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100),
    CPF VARCHAR(11),
    DATANASCIMENTO DATE,
    GENERO VARCHAR(50)
);

CREATE TABLE USUARIO(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    ADMIN BOOL DEFAULT FALSE
);

insert into usuario (login, password) values ('luizot', '$2a$12$1JQuhNXNz9FmJpjh0FtHrejJdFhBZBARe55JEI..s2MMyKdFd.ZZG');